## Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [2]:
data = pd.read_csv('C:/Users/jdblu/Documents/Data Science Practice/Linear Regression/MultLinearRegressionData.csv')

In [3]:
data.head()

SAT   GPA Attendance
0  1714  2.40         No
1  1664  2.52         No
2  1760  2.54         No
3  1685  2.74         No
4  1693  2.83         No

## Creating Regression Model

In [4]:
factored_data = data.copy()

In [5]:
factored_data['Attendance'] = data['Attendance'].map({'Yes':1, 'No':0})

### Standardization

In [7]:
from sklearn.preprocessing import StandardScaler

In [10]:
y = factored_data['GPA']
x = factored_data[['SAT', 'Attendance']]

scaler = StandardScaler()

In [11]:
scaler.fit(x)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [12]:
x_scaled = scaler.transform(x)

In [13]:
x_scaled

array([[-1.26338288, -0.93094934],
       [-1.74458431, -0.93094934],
       [-0.82067757, -0.93094934],
       [-1.54247971, -0.93094934],
       [-1.46548748, -0.93094934],
       [-1.68684014, -0.93094934],
       [-0.78218146, -0.93094934],
       [-0.78218146, -0.93094934],
       [-0.51270866, -0.93094934],
       [ 0.04548499, -0.93094934],
       [-1.06127829, -0.93094934],
       [-0.67631715, -0.93094934],
       [-1.06127829, -0.93094934],
       [-1.28263094, -0.93094934],
       [-0.6955652 , -0.93094934],
       [ 0.25721362,  1.07417231],
       [-0.86879772, -0.93094934],
       [-1.64834403,  1.07417231],
       [-0.03150724, -0.93094934],
       [-0.57045283,  1.07417231],
       [-0.81105355, -0.93094934],
       [-1.18639066, -0.93094934],
       [-1.75420834, -0.93094934],
       [-1.52323165, -0.93094934],
       [ 1.23886453, -0.93094934],
       [-0.18549169, -0.93094934],
       [-0.5608288 , -0.93094934],
       [-0.23361183, -0.93094934],
       [ 1.68156984,

### Regression with Scaled Features

In [14]:
reg = LinearRegression()
reg.fit(x_scaled,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [15]:
reg.coef_

array([0.14544861, 0.1110377 ])

In [16]:
reg.intercept_

3.330238095238095

### Creating Summary Table

In [17]:
reg_summary = pd.DataFrame([['Bias'],['SAT'],['Attendance']], columns=['Features'])
reg_summary['Weights'] = reg.intercept_, reg.coef_[0], reg.coef_[1]

In [18]:
reg_summary

Features   Weights
0        Bias  3.330238
1         SAT  0.145449
2  Attendance  0.111038

### Marking predictions with the standardized coefficients (weights)

In [19]:
new_data = pd.DataFrame(data=[[1700,1],[1800,0]], columns=['SAT','Attendance'])

In [20]:
new_data

SAT  Attendance
0  1700           1
1  1800           0

In [21]:
reg.predict(new_data)

array([250.70391216, 265.13773543])

In [22]:
new_data_scaled = scaler.transform(new_data)
new_data_scaled

array([[-1.39811928,  1.07417231],
       [-0.43571643, -0.93094934]])

In [23]:
reg.predict(new_data_scaled)

array([3.24615721, 3.16349328])