### Import Libraries

In [7]:
import numpy as np
from sklearn.model_selection import train_test_split

### Generating Data

In [3]:
a = np.arange(1,101)

In [4]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [5]:
b = np.arange(501, 601)

### Split Data

In [8]:
train_test_split(a)

[array([ 75,  66,  90,  10,  73,  34,  93,  19,  49,  87,  91,  61,  97,
         25,  76,   5,   4,  89,  72,  31,  13,  74,  80,  32,  12,  27,
         35,  67,  58,  60,  82,  38,   7,   6,  85,  42,  86,  26,  62,
         51,  88,   8, 100,  15,  30,  37,  16,  54,  23,  94,  11,  47,
         53,  24,  79,  68,  28,  81,  40,  56,  70,   1,  33,  43,  78,
         98,  36,  77,  45,  46,  95,  99,   2,  55,  63]),
 array([64, 14, 22,  9, 44, 21, 50, 83, 96, 57, 41,  3, 39, 84, 52, 29, 17,
        69, 20, 48, 92, 65, 71, 18, 59])]

In [29]:
a_train, a_test, b_train, b_test = train_test_split(a, b, test_size=0.2, random_state=42)

### Result Exploration

In [30]:
a_train.shape, a_test.shape

((80,), (20,))

In [31]:
a_train

array([ 56,  89,  27,  43,  70,  16,  41,  97,  10,  73,  12,  48,  86,
        29,  94,   6,  67,  66,  36,  17,  50,  35,   8,  96,  28,  20,
        82,  26,  63,  14,  25,   4,  18,  39,   9,  79,   7,  65,  37,
        90,  57, 100,  55,  44,  51,  68,  47,  69,  62,  98,  80,  42,
        59,  49,  99,  58,  76,  33,  95,  60,  64,  85,  38,  30,   2,
        53,  22,   3,  24,  88,  92,  75,  87,  83,  21,  61,  72,  15,
        93,  52])

In [32]:
a_test

array([84, 54, 71, 46, 45, 40, 23, 81, 11,  1, 19, 31, 74, 34, 91,  5, 77,
       78, 13, 32])

In [33]:
b_train.shape, b_test.shape

((80,), (20,))

In [34]:
b_train

array([556, 589, 527, 543, 570, 516, 541, 597, 510, 573, 512, 548, 586,
       529, 594, 506, 567, 566, 536, 517, 550, 535, 508, 596, 528, 520,
       582, 526, 563, 514, 525, 504, 518, 539, 509, 579, 507, 565, 537,
       590, 557, 600, 555, 544, 551, 568, 547, 569, 562, 598, 580, 542,
       559, 549, 599, 558, 576, 533, 595, 560, 564, 585, 538, 530, 502,
       553, 522, 503, 524, 588, 592, 575, 587, 583, 521, 561, 572, 515,
       593, 552])

In [35]:
b_test

array([584, 554, 571, 546, 545, 540, 523, 581, 511, 501, 519, 531, 574,
       534, 591, 505, 577, 578, 513, 532])